### ISSUE TITLE
SDRAM Memory Address on HPC VP

### ISSUE THREAD

**Issue by andstepan** [soc-hub-fi/headsail-vp#33] opened 2024-05-21 08:57 UTC
In [documentation](https://soc-hub.gitlab-pages.tuni.fi/headsail/hw/hpc-ss/hpcss_documentation.html#address-map) it is stated that "External Addresses" are mapped at address 0x1_0000_0000. In the VP's hpc.repl file, they are mapped at 0x1000_0000. Can we see what's going on?

**Comment by hegza** [comment] 2024-05-22 12:16
# Meeting outcomes

## Memory map investigation

- HPC needs the `0x1_0000_0000` "External access", when acting as the initiator, to access locations outside of the HPC subsystem
- HPC as initiator:
  - SDRAM starts at `0x1_0000_0000`
    - This has the external bit at `0x1_0000_0000` + SDRAM base at `0x0`
  - SDRAM len is `0x7000_0000`
  - HPC internal configurations are available via local map in locations `0x0..0x1_0000_0000` and via global map at `0x1_0000_0000 + HPC_config` offset.
- SysCtrl as initiator:
  - SDRAM starts at `0x1000_0000`
    - The first `0..0x1000_0000` are unavailable on SysCtrl due to legacy memory map.
    - HPC configurations are available via global map at  `HPC_config`
  - SDRAM len (truncated) is `0x6000_0000`

## Implementation on Renode (hardware view)

- common.repl
  ```repl
  sdram_truncated: Memory @ {
    sysbus new Bus.BusPointRegistration { address: 0x1000_0000; cpu: cpu_sysctrl };
    sysbus new Bus.BusPointRegistration { address: 0x1_1000_0000; cpu: cpu_hpc0, cpu_hpc1, cpu_hpc2, cpu_hpc3 };
    }
    size: 0x6000_0000
  ```
- hpc.repl
  ```repl
  // HPC-only visible part of the SDRAM
  sdram_hpc: Memory @ {
    sysbus new Bus.BusPointRegistration { address: 0x1_0000_0000; cpu: cpu_hpc0, cpu_hpc1, cpu_hpc2, cpu_hpc3 };
    }
    size: 0x1000_0000
  ```

## Impl in link script (software view)

```ld
// hpc-sdram.ld
MEMORY {
  SDRAM : ORIGIN = 0x1_0000_0000, LENGTH = 0x7000_0000 
}
```

```ld
// sysctrl-sdram.ld
MEMORY {
  SDRAM : ORIGIN = 0x1000_0000, LENGTH = 0x6000_0000 
}
```

**Comment by hegza** [comment] 2024-05-23 09:45
We confirmed in the meeting today that the above is correct.

**Comment by hegza** [comment] 2024-05-25 15:37
Correction: SysCtrl does not need the 0x1_0000_0000 external access bit to read from HPC configurations. (fixed in original message)

**Comment by hegza** [comment] 2024-06-14 10:41
We noticed that SysCtrl also has some peculiarities with regard to its memory map. When SysCtrl is the initiator, it uses the "Internal Address Map", when something else is the initiator, the "External Address Map" is to be used. The 3rd case is when HPC accesses SysCtrl: then we use both externals at the same time, i.e. SysCtrl external memory map + HPC external access bit.

[Internal Excel](https://tuni.sharepoint.com/:x:/r/sites/TG-SoC-Hub/_layouts/15/Doc.aspx?sourcedoc=%7BC5EB5E21-668C-430C-8E17-7BD5CFB663D6%7D&file=SysCtrl_Memory_Translation.xlsx&action=default&mobileredirect=true) describing the internal & external memory maps.

**Comment by hegza** [comment] 2024-08-06 13:24
Closing non-actionable issue in favor of a wiki page: https://github.com/soc-hub-fi/headsail-vp/wiki/Headsail-memory-maps

**Closed as completed by hegza** 2024-08-06 13:24 UTC
